language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
sudo: required
dist: trusty
script: make
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y emscripten
  - emcc || true
addons:
  apt:
    packages:
      - g++
      - libvorbis-dev
      - libogg-dev
notifications:
    email: false